### PR TITLE
Token Validation for API calls, fix #354

### LINKED ISSUE #354: API authentication regression
We've introduced a regression in https://github.com/developmentseed/osm-teams/pull/304/files#diff-7a3c45c30847eddded5f0bd2b2aab583e942f29d13fba0098225a61c9354268dL58 when migrating the API such that "stateless" tokens (non website-sessions) don't work anymore. We need to re-include stateless authentication to the API so that other third party applications can authenticate.

### PR DESCRIPTION
**Pull request by kamicut**
This implements:
1. token extraction from authorized API calls that have `Bearer <access_token>`
2. checks if the access token is valid by sending it to the `/introspect` route in the auth proxy (check https://github.com/developmentseed/osm-teams/commit/5470dc55bcf3ae808e5dfc22f6173ae01987b741)
3. extracts the `sub` trait from the resulting token and adds it to the session

This will allow API calls from third party applications to use access tokens to authenticate with the API.

I also added `isAuthenticated` for routes that need simply to have the session and session user ids in the `can` middleware.

### CODE REVIEW

**Comment by LanesGood** [comment]
@kamicut does this close issue 354?

**Comment by kamicut** [comment]
Yes! I forgot the issue number, it fixes #354

File: src/middlewares/base-handler.js [hunk 1]
```diff
@@ -1,6 +1,9 @@
 import nc from 'next-connect'
 import logger from '../lib/logger'
 import { getToken } from 'next-auth/jwt'
+import Boom from '@hapi/boom'
+
+const AUTH_URL = process.env.AUTH_URL || 'https://auth.mapping.team'
```
Comment (vgeorge) [inline src/middlewares/base-handler.js:6]: @kamicut it would be nice to move the default value to the next config file.

File: src/pages/api/auth/[...nextauth].js [hunk 2]
```diff
@@ -2,15 +2,16 @@ import NextAuth from 'next-auth'
 import { mergeDeepRight } from 'ramda'
 const db = require('../../../lib/db')
 
+const HYDRA_URL = process.env.HYDRA_URL || 'https://auth.mapping.team/hyauth'
+
```
Comment (vgeorge) [inline src/pages/api/auth/[...nextauth].js:6]: @kamicut it would be nice to move the default value to the next config file.

**Review by vgeorge — CHANGES_REQUESTED** [review]
@kamicut this look good overall, lets try to add test coverage for a HTTP agent, as discussed.

File: src/pages/api/introspect.js [hunk 3]
```diff
@@ -0,0 +1,24 @@
+const { decode } = require('next-auth/jwt')
+/**
+ * !! This function is only used for testing
+ * purposes, it mocks the hydra access token introspection
+ */
+export default async function handler(req, res) {
+  if (req.method === 'POST') {
```
Comment (vgeorge) [inline src/pages/api/introspect.js:7]: @kamicut I suggest adding a check here to avoid exposing this route outside testing:

```
if (process.env.TESTING !== 'true' || req.method !== 'POST') {
  throw Boom.notFound()
}
```

**Review by vgeorge — CHANGES_REQUESTED** [review]
@kamicut I think we are almost there, should we add a test for a route in 'manage' folder?

**Review by vgeorge — APPROVED** [review]
